name: CI/CD

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: my-project
  BUCKET_NAME: my-s3-bucket
  CODE_DEPLOY_APP_NAME: my-codedeploy-app
  DEPLOYMENT_GROUP_NAME: my-codedeploy-group

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
	
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
