name: CI/CD

on:
  push:
    branches:
      - dev

env:
  PROJECT_NAME: my-project
  BUCKET_NAME: my-s3-bucket
  CODE_DEPLOY_APP_NAME: my-codedeploy-app
  DEPLOYMENT_GROUP_NAME: my-codedeploy-group

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          # 여기에 머가 문제인데~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          # 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Make Zip File
        run: zip -qq -r ./app.zip .
      #aws
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEYID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secret.AWS_REGION }}
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./app.zip s3://$BUCKET_NAME/$PROJECT_NAME/app.zip
      
      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/app.zip
